# Generated by Django 4.2.13 on 2025-02-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_project_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='coins.job'),
        ),
    ]
