# Generated by Django 4.2.13 on 2025-02-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_project_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='job', serialize=False, to='coins.project'),
            preserve_default=False,
        ),
    ]
