# Generated by Django 4.2.13 on 2024-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('desc_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('closed', models.IntegerField(blank=True, null=True)),
                ('pinned', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('short_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
                ('prefs', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
            ],
            options={
                'db_table': 'Bronze].[trello_board',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('badges_location', models.IntegerField(blank=True, null=True)),
                ('badges_votes', models.IntegerField(blank=True, null=True)),
                ('badges_viewing_member_voted', models.IntegerField(blank=True, null=True)),
                ('badges_subscribed', models.IntegerField(blank=True, null=True)),
                ('badges_fogbugz', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('badges_check_items', models.IntegerField(blank=True, null=True)),
                ('badges_check_items_checked', models.IntegerField(blank=True, null=True)),
                ('badges_comments', models.IntegerField(blank=True, null=True)),
                ('badges_attachments', models.IntegerField(blank=True, null=True)),
                ('badges_description', models.IntegerField(blank=True, null=True)),
                ('badges_due', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('badges_start', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('badges_due_complete', models.IntegerField(blank=True, null=True)),
                ('check_item_states', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('closed', models.IntegerField(blank=True, null=True)),
                ('coordinates', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('creation_method', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('date_last_activity', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('description_data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('due_reminder', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('id_short', models.IntegerField(blank=True, null=True)),
                ('id_attachment_cover', models.CharField(blank=True, max_length=36, null=True)),
                ('location_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('manual_cover_attachment', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('pos', models.IntegerField(blank=True, null=True)),
                ('short_link', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('short_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
            ],
            options={
                'db_table': 'Bronze].[trello_card',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
            ],
            options={
                'db_table': 'Bronze].[trello_customfield',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
            ],
            options={
                'db_table': 'Bronze].[trello_enterprise',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MissingAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('data', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('display', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Bronze].[trello_missingaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('model_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('model_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bronze].[trello_webhook',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=500)),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.enterprise')),
            ],
            options={
                'db_table': 'Bronze].[trello_workspace',
                'ordering': ['display_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=500)),
                ('full_name', models.CharField(blank=True, default='', max_length=50)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.enterprise')),
                ('workspaces', models.ManyToManyField(blank=True, to='trello.workspace')),
            ],
            options={
                'db_table': 'Bronze].[trello_member',
                'ordering': ['full_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
            ],
            options={
                'db_table': 'Bronze].[trello_list',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', default='', max_length=50)),
                ('color', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.board')),
            ],
            options={
                'db_table': 'Bronze].[trello_label',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('value', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('CustomField', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.customfield')),
            ],
            options={
                'db_table': 'Bronze].[trello_customfieldoption',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomFieldItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('value', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.card')),
                ('customField', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.customfield')),
                ('customFieldOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.customfieldoption')),
            ],
            options={
                'db_table': 'Bronze].[trello_customfielditem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default='1999-12-30 12:00')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.card')),
            ],
            options={
                'db_table': 'Bronze].[trello_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.card')),
            ],
            options={
                'db_table': 'Bronze].[trello_checklist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('name', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('state', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.checklist')),
            ],
            options={
                'db_table': 'Bronze].[trello_checkitem',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='labels',
            field=models.ManyToManyField(to='trello.label'),
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.list'),
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(to='trello.member'),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(to='trello.member'),
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.workspace'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trello_id', models.CharField(max_length=50)),
                ('data', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('limits', models.TextField(blank=True, null=True)),
                ('display', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.member')),
                ('webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.webhook')),
            ],
            options={
                'db_table': 'Bronze].[trello_action',
                'managed': True,
            },
        ),
    ]
