"""
Django settings for am_nexus project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path
import os
import ldap
import logging
from django_auth_ldap.config import ActiveDirectoryGroupType, LDAPSearch, LDAPSearchUnion, NestedActiveDirectoryGroupType
from dotenv import load_dotenv, find_dotenv

# sticking the env at the top so it can be used farther down
# load the .env file from ../
load_dotenv(find_dotenv())

# assign the environment variables
DATABASE_SERVER     = os.environ['SERVER']
DATABASE_NAME       = os.environ['DATABASE_NAME']
DATABASE_USERNAME   = os.environ['DATABASE_USERNAME']
DATABASE_PASSWORD   = os.environ['DATABASE_PASSWORD']
TRIMBLE_BASE_URL    = os.environ.get('TRIMBLE_BASE_URL')
ACCUBID_BASE_URL    = os.environ.get('ACCUBID_BASE_URL')
CLIENT_ID           = os.environ.get('CLIENT_ID')
CLIENT_SECRET       = os.environ.get('CLIENT_SECRET')
APP_NAME            = os.environ.get('APP_NAME')
CODE_CHALLENGE      = os.environ.get('CODE_CHALLENGE')
CODE_VERIFIER       = os.environ.get('CODE_VERIFIER')
LDAP_PASSWORD       = os.environ.get('LDAP_PASSWORD')
WINDOWS_USERNAME    = os.environ.get('WINDOWS_USERNAME')
WINDOWS_PASSWORD    = os.environ.get('WINDOWS_PASSWORD')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# Trello keys
TRELLO_KEY   = os.environ['TRELLO_KEY']
TRELLO_TOKEN = os.environ['TRELLO_TOKEN']

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "class": "logging.FileHandler",
            "filename": "./general.log",
            "formatter": "simple",
        },
    },
    "loggers": {
        "": {
            "level": "DEBUG",
            "handlers": ["file"],
            "propogate": True,
        },
    },
    "formatters": {
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
}

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ['ALLOWED_HOSTS'].split(',')
# Application definition

INSTALLED_APPS = [
    # Custom Apps
    'skillAssessments',
    'trello',
    'forms',
    'coins.apps.CoinsConfig',
    'menu_app',
    'search_select',
    'accubid',
    'accounts',
    'box',
    'liquid_cloud',
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    'django_filters',
    'debug_toolbar',
    'django_auth_ldap',
    'django_celery_beat',
    'rest_framework_datatables',
    'rest_framework',
    'import_export',
    'jsignature',
    'mssql',
]

IMPORT_EXPORT_USE_TRANSACTIONS = True

INTERNAL_IPS = [
        '127.0.0.1',
        '172.29.80.1',
        '10.66.48.147',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
}
ROOT_URLCONF = 'am_nexus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'menu_app.context_processors.menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'am_nexus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_SERVER,
        'OPTIONS': {'driver': 'ODBC Driver 17 for SQL Server'},
    },
    'bronze': {
        'ENGINE': 'mssql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_SERVER,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'options': '-c search_path=Bronze'
        },
    },
    'silver': {
        'ENGINE': 'mssql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_SERVER,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'options': '-c search_path=silver'
        },
    },
    'gold': {
        'ENGINE': 'mssql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_SERVER,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'options': '-c search_path=gold'
        },
    },
    'dbo': {
        'ENGINE': 'mssql',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USERNAME,
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': DATABASE_SERVER,
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'options': '-c search_path=dbo'
        },
    }
}

DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_L10N      = True
USE_TZ        = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/home/ateam/py-AM-Nexus/Middleware/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'globalstatic'
]

CSRF_TRUSTED_ORIGINS = [
        'http://amcloud.amteck.com:8002',
]

CELERY_BROKER_URL     = 'amqp://localhost:5672//'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

APPEND_SLASH = False

JSIGNATURE_JQUERY = 'admin'

# Login settings
AUTH_USER_MODEL     = 'accounts.CustomUser' # Custom user model
LOGIN_REDIRECT_URL  = '/'
LOGIN_URL           = '/accounts/login/'
LOGOUT_REDIRECT_URL = 'https://amteck.com'
LOGOUT_URL          = '/accounts/logout/'

AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
]

# LDAP settings
AUTH_LDAP_SERVER_URI    = os.environ['LDAP_SERVER_URI'] 
AUTH_LDAP_BIND_DN       = "CN=AMT WebApp LDAP,OU=AMT Service Accounts,OU=Region 02 Service Accounts,OU=Operating Location Service Accounts,OU=Privileged Service Accounts,OU=IT Team,DC=cs,DC=loc"
AUTH_LDAP_BIND_PASSWORD = LDAP_PASSWORD
AUTH_LDAP_GROUP_TYPE    = NestedActiveDirectoryGroupType(name_attr="cn")
AUTH_LDAP_USER_SEARCH   = LDAPSearch(
    "ou=amt users,ou=region 02 users,ou=operating location users,ou=operating locations,dc=cs,dc=loc",
    ldap.SCOPE_SUBTREE,
    "(&(objectClass=user)(proxyAddresses=smtp:%(user)s))"
)

AUTH_LDAP_GROUP_SEARCH = LDAPSearchUnion(
    LDAPSearch(
        "ou=amt security groups,ou=region 02 security groups,ou=operating location security groups,ou=operating locations,dc=cs,dc=loc", 
        ldap.SCOPE_SUBTREE, 
        "(objectClass=group)"
    ),
    LDAPSearch(
        "ou=amt distribution groups,ou=region 02 distribution groups,ou=operating location distribution groups,ou=operating locations,dc=cs,dc=loc", 
        ldap.SCOPE_SUBTREE, 
        "(objectClass=group)"
    )
)
# Populate the Django user from the LDAP directory.
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_FIND_GROUP_PERMS   = True
AUTH_LDAP_CACHE_TIMEOUT      = 3600

AUTH_LDAP_CONNECTION_OPTIONS = { ldap.OPT_DEBUG_LEVEL: 1, ldap.OPT_REFERRALS: 0,}

# LDAP group to Django group mapping
AUTH_LDAP_GROUP_MAPPING = {
   "AMT01-Lexington Office": "amtlg-accounting",
   "cn=amtlg-purchasing,ou=amt security groups,ou=region 02 security groups,ou=operating location security groups,ou=operating locations,dc=cs,dc=loc": "amtlg-purchasing",
}

# Logging for LDAP
logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)
