# Generated by Django 4.2.13 on 2024-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'database',
                'verbose_name_plural': 'databases',
                'db_table': 'Bronze].[accubid_database',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=200)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('managingBranchName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('projectPath', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('trimbleProjectId', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('siteName', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sitePhone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('siteFax', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('siteStreet1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('siteStreet2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('siteCity', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('siteState', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('siteZip', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('siteCountry', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.employee')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'Bronze].[accubid_project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('number', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=50)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=200, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('laborColumn', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('laborFactorMethod', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('imperialMetric', models.CharField(blank=True, choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='', max_length=50, null=True)),
                ('industry', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('applyMarkupOnOverhead', models.BooleanField(default=False)),
                ('applyOverheadAndMarkupOnTax', models.BooleanField(default=False)),
                ('vendorPricingPrecedence', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timeInterval', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.employee')),
            ],
            options={
                'verbose_name': 'estimate',
                'verbose_name_plural': 'estimates',
                'db_table': 'Bronze].[accubid_estimate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BidSummary',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidSummaries', to='accubid.estimate')),
            ],
            options={
                'verbose_name': 'bid summary',
                'verbose_name_plural': 'bid summaries',
                'db_table': 'Bronze].[accubid_bid_summary',
                'managed': True,
            },
        ),
    ]
