# Generated by Django 4.2.13 on 2024-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FolderSearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=100)),
                ('search_term', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Folder Search Term',
                'verbose_name_plural': 'Folder Search Terms',
                'db_table': 'folder_search_terms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project Folder',
                'verbose_name_plural': 'Project Folders',
                'db_table': 'project_folders',
                'ordering': ['sta'],
                'managed': True,
            },
        ),
    ]
