# Generated by Django 4.2.13 on 2024-11-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFolders',
        ),
    ]
