# Generated by Django 4.2.13 on 2024-11-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('box', '0002_delete_projectfolders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.project')),
            ],
            options={
                'verbose_name': 'Project Folder',
                'verbose_name_plural': 'Project Folders',
                'db_table': 'Bronze].[project_folders',
                'ordering': ['sta'],
                'managed': True,
            },
        ),
    ]
