# Generated by Django 4.2.13 on 2024-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, choices=[('fa-list', 'Report'), ('fa-user', 'User'), ('fa-file-contract', 'Form'), ('fa-chart-simple', 'Dashboard')], max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='menu_app.menuitem')),
            ],
            options={
                'db_table': 'menuapp_menuitem',
                'managed': True,
            },
        ),
    ]
