# Generated by Django 4.2.13 on 2024-11-19 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recorded_at')),
                ('is_self_assessment', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'Bronze].[skills_assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'Bronze].[skills_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('order', models.CharField(blank=True, max_length=3, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillAssessments.category')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'Bronze].[skills_skill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coins.employee')),
                ('is_assessor', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_onsite', to='coins.job', verbose_name='Current Job')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'Bronze].[skills_user',
                'managed': True,
            },
            bases=('coins.employee',),
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(choices=[(0, '0 - Not Observed'), (1, '1 - Needs Development'), (2, '2 - Intermediate Knowledge'), (3, '3 - Solid Knowledge'), (4, '4 - Advanced Knowledge')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='skillAssessments.assessment', verbose_name='Assessment')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='skillAssessments.skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Skill Score',
                'verbose_name_plural': 'Skill Scores',
                'db_table': 'Bronze].[skills_skill_score',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_assessor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments_given', to='skillAssessments.user', verbose_name='Assessor'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='coins.job', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='skill_scores',
            field=models.ManyToManyField(through='skillAssessments.SkillScore', to='skillAssessments.skill'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='skillAssessments.user', verbose_name='Employee'),
        ),
    ]
