# Generated by Django 4.2.13 on 2024-11-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillAssessments', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='skill',
    #         name='order',
    #         field=models.IntegerField(blank=True, null=True),
    #     ),
    # ]
