# Generated by Django 4.2.13 on 2024-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillAssessments', '0002_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
