# Generated by Django 4.2.13 on 2024-11-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillAssessments', '0003_alter_skill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
