# Generated by Django 4.2.13 on 2024-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillAssessments', '0004_alter_skill_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
