# Generated by Django 4.2.13 on 2024-12-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('skillAssessments', '0005_assessment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='coins.job', verbose_name='Project'),
        ),
    ]
