# Generated by Django 4.2.13 on 2025-01-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='project',
            field=models.ForeignKey(limit_choices_to={'job_active': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='coins.job'),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='spotter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starequiredemployeecertification',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starequiredpermit',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='starequiredprocedure',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='starequiredspecialcertification',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
