# Generated by Django 4.2.13 on 2025-01-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_safetytaskanalysisresponse_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staemployeeacknowledgement',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='starequiredemployeecertification',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
