# Generated by Django 4.2.13 on 2025-01-20 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_alter_staemployeeacknowledgement_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetytaskanalysisresponse',
            name='assessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
