# Generated by Django 4.2.13 on 2025-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_safetytaskanalysisresponse_assessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetytaskanalysisresponse',
            old_name='project',
            new_name='job',
        ),
    ]
