# Generated by Django 4.2.13 on 2025-02-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_rename_project_safetytaskanalysisresponse_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='foreman_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='lead_superintendent_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='manager_phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
