# Generated by Django 4.2.13 on 2025-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_safetytaskanalysisresponse_assessor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetytaskanalysisresponse',
            name='boxID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
