# Generated by Django 4.2.13 on 2025-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_safetytaskanalysisresponse_boxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='boxID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
