# Generated by Django 4.2.13 on 2025-03-13 13:43

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_safetytaskanalysisresponse_boxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_approve_printed_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_approve_signature',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_height',
            field=models.CharField(blank=True, choices=[('6', "6'"), ('8', "8'"), ('10', "10'")], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_reason_for_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_type',
            field=models.CharField(blank=True, choices=[('aframe', 'A-Frame'), ('platform', 'Platform')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ladder_work_elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='lift',
            field=models.CharField(blank=True, choices=[('Scissor', (('sc19', "19' Scissor"), ('sc26', "26' Scissor"), ('sc32', "32' Scissor"), ('sc', 'Other'))), ('Booms', (('art45', "45' Art Boom"), ('art', 'Other'))), ('unknown', 'Unknown')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='safetytaskanalysisresponse',
            name='ppe',
            field=models.ManyToManyField(blank=True, null=True, to='forms.stappe'),
        ),
    ]
